version: "3.8"

services:

  mongodb:
    image: mongo:6.0.4
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    healthcheck:
      test: "echo 'db.stats().ok' | mongosh localhost:27017/moviedb --quiet"
